export const LAST_UPDATED = 'March 2026';

export const AIRLINES = [
  {
    code: '0B',
    name: 'Blue Air',
    country: 'Romania',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Blue_Air',
  },
  {
    code: '2B',
    name: 'Aerocondor',
    country: 'Portugal',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Aerocondor',
  },
  {
    code: '3K',
    name: 'Jetstar Asia',
    country: 'Singapore',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jetstar_Asia',
  },
  {
    code: '3U',
    name: 'Sichuan Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Sichuan_Airlines',
  },
  {
    code: '3X',
    name: 'Japan Air Commuter',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Japan_Air_Commuter',
  },
  {
    code: '4C',
    name: 'Aires',
    country: 'Colombia',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Aires',
  },
  {
    code: '4M',
    name: 'LAN Argentina',
    country: 'Argentina',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LAN_Argentina',
  },
  {
    code: '4O',
    name: 'Interjet',
    country: 'Mexico',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Interjet',
  },
  {
    code: '4U',
    name: 'Germanwings',
    country: 'Germany',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Germanwings',
  },
  {
    code: '4Z',
    name: 'Airlink',
    country: 'South Africa',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Airlink',
  },
  {
    code: '5J',
    name: 'Cebu Pacific',
    country: 'Philippines',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Cebu_Pacific',
  },
  {
    code: '5X',
    name: 'UPS Airlines',
    country: 'USA',
    region: 'Other',
    wiki: 'https://en.wikipedia.org/wiki/UPS_Airlines',
  },
  {
    code: '6E',
    name: 'IndiGo',
    country: 'India',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/IndiGo',
  },
  {
    code: '7C',
    name: 'Jeju Air',
    country: 'South Korea',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jeju_Air',
  },
  {
    code: '7G',
    name: 'StarFlyer',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/StarFlyer',
  },
  {
    code: '9W',
    name: 'Jet Airways',
    country: 'India',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jet_Airways',
  },
  {
    code: 'A3',
    name: 'Aegean Airlines',
    country: 'Greece',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Aegean_Airlines',
  },
  {
    code: 'AA',
    name: 'American Airlines',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/American_Airlines',
  },
  {
    code: 'AB',
    name: 'Air Berlin',
    country: 'Germany',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_Berlin',
  },
  {
    code: 'AC',
    name: 'Air Canada',
    country: 'Canada',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Air_Canada',
  },
  {
    code: 'AD',
    name: 'Azul Brazilian Airlines',
    country: 'Brazil',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Azul_Brazilian_Airlines',
  },
  {
    code: 'AF',
    name: 'Air France',
    country: 'France',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_France',
  },
  {
    code: 'AH',
    name: 'Air Algerie',
    country: 'Algeria',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Air_Algerie',
  },
  {
    code: 'AI',
    name: 'Air India',
    country: 'India',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_India',
  },
  {
    code: 'AK',
    name: 'AirAsia',
    country: 'Malaysia',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/AirAsia',
  },
  {
    code: 'AM',
    name: 'Aeromexico',
    country: 'Mexico',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Aeromexico',
  },
  {
    code: 'AR',
    name: 'Aerolineas Argentinas',
    country: 'Argentina',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Aerolineas_Argentinas',
  },
  {
    code: 'AS',
    name: 'Alaska Airlines',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Alaska_Airlines',
  },
  {
    code: 'AT',
    name: 'Royal Air Maroc',
    country: 'Morocco',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Royal_Air_Maroc',
  },
  {
    code: 'AV',
    name: 'Avianca',
    country: 'Colombia',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Avianca',
  },
  {
    code: 'AY',
    name: 'Finnair',
    country: 'Finland',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Finnair',
  },
  {
    code: 'AZ',
    name: 'ITA Airways',
    country: 'Italy',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/ITA_Airways',
  },
  {
    code: 'B2',
    name: 'Belavia',
    country: 'Belarus',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Belavia',
  },
  {
    code: 'B6',
    name: 'JetBlue Airways',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/JetBlue_Airways',
  },
  {
    code: 'B7',
    name: 'Uni Air',
    country: 'Taiwan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Uni_Air',
  },
  {
    code: 'BA',
    name: 'British Airways',
    country: 'United Kingdom',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/British_Airways',
  },
  {
    code: 'BC',
    name: 'Skymark Airlines',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Skymark_Airlines',
  },
  {
    code: 'BE',
    name: 'Flybe',
    country: 'United Kingdom',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Flybe_(2022-2023)',
  },
  {
    code: 'BG',
    name: 'Biman Bangladesh Airlines',
    country: 'Bangladesh',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Biman_Bangladesh_Airlines',
  },
  {
    code: 'BI',
    name: 'Royal Brunei Airlines',
    country: 'Brunei',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Royal_Brunei_Airlines',
  },
  {
    code: 'BL',
    name: 'Jetstar Pacific',
    country: 'Vietnam',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jetstar_Pacific',
  },
  {
    code: 'BP',
    name: 'Air Botswana',
    country: 'Botswana',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Air_Botswana',
  },
  {
    code: 'BR',
    name: 'EVA Air',
    country: 'Taiwan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/EVA_Air',
  },
  {
    code: 'BT',
    name: 'Air Baltic',
    country: 'Latvia',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_Baltic',
  },
  {
    code: 'BV',
    name: 'Blue Panorama Airlines',
    country: 'Italy',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Blue_Panorama_Airlines',
  },
  {
    code: 'BY',
    name: 'TUI Airways',
    country: 'UK',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/TUI_Airways',
  },
  {
    code: 'CA',
    name: 'Air China',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_China',
  },
  {
    code: 'CI',
    name: 'China Airlines',
    country: 'Taiwan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/China_Airlines',
  },
  {
    code: 'CK',
    name: 'China Cargo Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/China_Cargo_Airlines',
  },
  {
    code: 'CM',
    name: 'Copa Airlines',
    country: 'Panama',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Copa_Airlines',
  },
  {
    code: 'CU',
    name: 'Cubana de Aviacion',
    country: 'Cuba',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Cubana_de_Aviacion',
  },
  {
    code: 'CX',
    name: 'Cathay Pacific',
    country: 'Hong Kong',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Cathay_Pacific',
  },
  {
    code: 'CZ',
    name: 'China Southern Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/China_Southern_Airlines',
  },
  {
    code: 'D7',
    name: 'AirAsia X',
    country: 'Malaysia',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/AirAsia_X',
  },
  {
    code: 'DD',
    name: 'Nok Air',
    country: 'Thailand',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Nok_Air',
  },
  {
    code: 'DL',
    name: 'Delta Air Lines',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Delta_Air_Lines',
  },
  {
    code: 'DT',
    name: 'TAAG Angola Airlines',
    country: 'Angola',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/TAAG_Angola_Airlines',
  },
  {
    code: 'DX',
    name: 'DAT Danish Air Transport',
    country: 'Denmark',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/DAT_Danish_Air_Transport',
  },
  {
    code: 'DY',
    name: 'Norwegian Air Shuttle',
    country: 'Norway',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Norwegian_Air_Shuttle',
  },
  {
    code: 'EI',
    name: 'Aer Lingus',
    country: 'Ireland',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Aer_Lingus',
  },
  {
    code: 'EK',
    name: 'Emirates',
    country: 'UAE',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Emirates_(airline)',
  },
  {
    code: 'ET',
    name: 'Ethiopian Airlines',
    country: 'Ethiopia',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Ethiopian_Airlines',
  },
  {
    code: 'EW',
    name: 'Eurowings',
    country: 'Germany',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Eurowings',
  },
  {
    code: 'EY',
    name: 'Etihad Airways',
    country: 'UAE',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Etihad_Airways',
  },
  {
    code: 'F9',
    name: 'Frontier Airlines',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Frontier_Airlines',
  },
  {
    code: 'FB',
    name: 'Bulgaria Air',
    country: 'Bulgaria',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Bulgaria_Air',
  },
  {
    code: 'FD',
    name: 'Thai AirAsia',
    country: 'Thailand',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Thai_AirAsia',
  },
  {
    code: 'FI',
    name: 'Icelandair',
    country: 'Iceland',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Icelandair',
  },
  {
    code: 'FJ',
    name: 'Fiji Airways',
    country: 'Fiji',
    region: 'Oceania',
    wiki: 'https://en.wikipedia.org/wiki/Fiji_Airways',
  },
  {
    code: 'FL',
    name: 'AirTran Airways',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/AirTran_Airways',
  },
  {
    code: 'FM',
    name: 'Shanghai Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Shanghai_Airlines',
  },
  {
    code: 'FR',
    name: 'Ryanair',
    country: 'Ireland',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Ryanair',
  },
  {
    code: 'FX',
    name: 'FedEx Express',
    country: 'USA',
    region: 'Other',
    wiki: 'https://en.wikipedia.org/wiki/FedEx_Express',
  },
  {
    code: 'FY',
    name: 'Firefly',
    country: 'Malaysia',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Firefly_(airline)',
  },
  {
    code: 'FZ',
    name: 'flydubai',
    country: 'UAE',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Flydubai',
  },
  {
    code: 'G3',
    name: 'GOL',
    country: 'Brazil',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Gol_Linhas_Aéreas_Inteligentes',
  },
  {
    code: 'G4',
    name: 'Allegiant Air',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Allegiant_Air',
  },
  {
    code: 'G8',
    name: 'GoAir',
    country: 'India',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/GoAir',
  },
  {
    code: 'G9',
    name: 'Air Arabia',
    country: 'UAE',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Air_Arabia',
  },
  {
    code: 'GA',
    name: 'Garuda Indonesia',
    country: 'Indonesia',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Garuda_Indonesia',
  },
  {
    code: 'GE',
    name: 'TransAsia Airways',
    country: 'Taiwan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/TransAsia_Airways',
  },
  {
    code: 'GF',
    name: 'Gulf Air',
    country: 'Bahrain',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Gulf_Air',
  },
  {
    code: 'GK',
    name: 'Jetstar Japan',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jetstar_Japan',
  },
  {
    code: 'GL',
    name: 'Air Greenland',
    country: 'Denmark',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_Greenland',
  },
  {
    code: 'H2',
    name: 'SKY Airline',
    country: 'Chile',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/Sky_Airline',
  },
  {
    code: 'HA',
    name: 'Hawaiian Airlines',
    country: 'USA',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Hawaiian_Airlines',
  },
  {
    code: 'HD',
    name: 'Air Do',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_Do',
  },
  {
    code: 'HM',
    name: 'Air Seychelles',
    country: 'Seychelles',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Air_Seychelles',
  },
  {
    code: 'HO',
    name: 'Juneyao Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Juneyao_Airlines',
  },
  {
    code: 'HU',
    name: 'Hainan Airlines',
    country: 'China',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Hainan_Airlines',
  },
  {
    code: 'HV',
    name: 'Transavia',
    country: 'Netherlands',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Transavia',
  },
  {
    code: 'HX',
    name: 'Hong Kong Airlines',
    country: 'Hong Kong',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Hong_Kong_Airlines',
  },
  {
    code: 'HY',
    name: 'Uzbekistan Airways',
    country: 'Uzbekistan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Uzbekistan_Airways',
  },
  {
    code: 'IA',
    name: 'Iraqi Airways',
    country: 'Iraq',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Iraqi_Airways',
  },
  {
    code: 'IB',
    name: 'Iberia',
    country: 'Spain',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Iberia_(airline)',
  },
  {
    code: 'IR',
    name: 'Iran Air',
    country: 'Iran',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Iran_Air',
  },
  {
    code: 'IX',
    name: 'Air India Express',
    country: 'India',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_India_Express',
  },
  {
    code: 'IY',
    name: 'Yemenia',
    country: 'Yemen',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Yemenia',
  },
  {
    code: 'J2',
    name: 'Azerbaijan Airlines',
    country: 'Azerbaijan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Azerbaijan_Airlines',
  },
  {
    code: 'J9',
    name: 'Jazeera Airways',
    country: 'Kuwait',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Jazeera_Airways',
  },
  {
    code: 'JJ',
    name: 'LATAM Brasil',
    country: 'Brazil',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LATAM_Brasil',
  },
  {
    code: 'JK',
    name: 'Spanair',
    country: 'Spain',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Spanair',
  },
  {
    code: 'JL',
    name: 'Japan Airlines',
    country: 'Japan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Japan_Airlines',
  },
  {
    code: 'JQ',
    name: 'Jetstar Airways',
    country: 'Australia',
    region: 'Oceania',
    wiki: 'https://en.wikipedia.org/wiki/Jetstar_Airways',
  },
  {
    code: 'JS',
    name: 'Air Koryo',
    country: 'North Korea',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_Koryo',
  },
  {
    code: 'JT',
    name: 'Lion Air',
    country: 'Indonesia',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Lion_Air',
  },
  {
    code: 'JU',
    name: 'Air Serbia',
    country: 'Serbia',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_Serbia',
  },
  {
    code: 'KA',
    name: 'Dragonair',
    country: 'Hong Kong',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Dragonair',
  },
  {
    code: 'KB',
    name: 'Druk Air',
    country: 'Bhutan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Druk_Air',
  },
  {
    code: 'KC',
    name: 'Air Astana',
    country: 'Kazakhstan',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_Astana',
  },
  {
    code: 'KE',
    name: 'Korean Air',
    country: 'South Korea',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Korean_Air',
  },
  {
    code: 'KL',
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/KLM_Royal_Dutch_Airlines',
  },
  {
    code: 'KM',
    name: 'Air Malta',
    country: 'Malta',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Air_Malta',
  },
  {
    code: 'KQ',
    name: 'Kenya Airways',
    country: 'Kenya',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Kenya_Airways',
  },
  {
    code: 'KU',
    name: 'Kuwait Airways',
    country: 'Kuwait',
    region: 'Middle East',
    wiki: 'https://en.wikipedia.org/wiki/Kuwait_Airways',
  },
  {
    code: 'KX',
    name: 'Cayman Airways',
    country: 'Cayman Islands',
    region: 'North America',
    wiki: 'https://en.wikipedia.org/wiki/Cayman_Airways',
  },
  {
    code: 'LA',
    name: 'LATAM Airlines',
    country: 'Chile',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LATAM_Airlines',
  },
  {
    code: 'LD',
    name: 'Air Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Air_Hong_Kong',
  },
  {
    code: 'LG',
    name: 'Luxair',
    country: 'Luxembourg',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Luxair',
  },
  {
    code: 'LH',
    name: 'Lufthansa',
    country: 'Germany',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Lufthansa',
  },
  {
    code: 'LJ',
    name: 'Jin Air',
    country: 'South Korea',
    region: 'Asia',
    wiki: 'https://en.wikipedia.org/wiki/Jin_Air',
  },
  {
    code: 'LM',
    name: 'LAM Mozambique Airlines',
    country: 'Mozambique',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/LAM_Mozambique_Airlines',
  },
  {
    code: 'LN',
    name: 'Libyan Airlines',
    country: 'Libya',
    region: 'Africa',
    wiki: 'https://en.wikipedia.org/wiki/Libyan_Airlines',
  },
  {
    code: 'LO',
    name: 'LOT Polish Airlines',
    country: 'Poland',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/LOT_Polish_Airlines',
  },
  {
    code: 'LP',
    name: 'LAN Peru',
    country: 'Peru',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LAN_Peru',
  },
  {
    code: 'LR',
    name: 'LACSA',
    country: 'Costa Rica',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LACSA',
  },
  {
    code: 'LS',
    name: 'Jet2',
    country: 'United Kingdom',
    region: 'Europe',
    wiki: 'https://en.wikipedia.org/wiki/Jet2.com',
  },
  {
    code: 'LU',
    name: 'LAN Express',
    country: 'Chile',
    region: 'Latin America',
    wiki: 'https://en.wikipedia.org/wiki/LAN_Express',
  },
  { code: 'LX', name: 'Swiss', country: 'Switzerland', region: 'Europe' },
  {
    code: 'MA',
    name: 'Malev Hungarian Airlines',
    country: 'Hungary',
    region: 'Europe',
  },
  {
    code: 'MD',
    name: 'Air Madagascar',
    country: 'Madagascar',
    region: 'Africa',
  },
  {
    code: 'ME',
    name: 'Middle East Airlines',
    country: 'Lebanon',
    region: 'Middle East',
  },
  {
    code: 'MF',
    name: 'Xiamen Airlines',
    country: 'China',
    region: 'Asia',
  },
  {
    code: 'MH',
    name: 'Malaysia Airlines',
    country: 'Malaysia',
    region: 'Asia',
  },
  { code: 'MI', name: 'SilkAir', country: 'Singapore', region: 'Asia' },
  {
    code: 'MK',
    name: 'Air Mauritius',
    country: 'Mauritius',
    region: 'Africa',
  },
  {
    code: 'MM',
    name: 'Peach Aviation',
    country: 'Japan',
    region: 'Asia',
  },
  {
    code: 'MQ',
    name: 'American Eagle',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'MS',
    name: 'Egyptair',
    country: 'Egypt',
    region: 'Middle East',
  },
  {
    code: 'MU',
    name: 'China Eastern Airlines',
    country: 'China',
    region: 'Asia',
  },
  {
    code: 'MX',
    name: 'Mexicana',
    country: 'Mexico',
    region: 'Latin America',
  },
  {
    code: 'NF',
    name: 'Air Vanuatu',
    country: 'Vanuatu',
    region: 'Oceania',
  },
  {
    code: 'NH',
    name: 'All Nippon Airways',
    country: 'Japan',
    region: 'Asia',
  },
  {
    code: 'NK',
    name: 'Spirit Airlines',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'NT',
    name: 'Binter Canarias',
    country: 'Spain',
    region: 'Europe',
  },
  {
    code: 'NU',
    name: 'Japan Transocean Air',
    country: 'Japan',
    region: 'Asia',
  },
  {
    code: 'NW',
    name: 'Northwest Airlines',
    country: 'USA',
    region: 'North America',
  },
  { code: 'NX', name: 'Air Macao', country: 'Macau', region: 'Asia' },
  {
    code: 'NZ',
    name: 'Air New Zealand',
    country: 'New Zealand',
    region: 'Oceania',
  },
  {
    code: 'OA',
    name: 'Olympic Airlines',
    country: 'Greece',
    region: 'Europe',
  },
  {
    code: 'OB',
    name: 'Boliviana de Aviacion',
    country: 'Bolivia',
    region: 'Latin America',
  },
  {
    code: 'OK',
    name: 'Czech Airlines',
    country: 'Czech Republic',
    region: 'Europe',
  },
  {
    code: 'OS',
    name: 'Austrian Airlines',
    country: 'Austria',
    region: 'Europe',
  },
  {
    code: 'OU',
    name: 'Croatia Airlines',
    country: 'Croatia',
    region: 'Europe',
  },
  {
    code: 'OZ',
    name: 'Asiana Airlines',
    country: 'South Korea',
    region: 'Asia',
  },
  {
    code: 'P2',
    name: 'Airkenya Express',
    country: 'Kenya',
    region: 'Africa',
  },
  {
    code: 'PD',
    name: 'Porter Airlines',
    country: 'Canada',
    region: 'North America',
  },
  {
    code: 'PG',
    name: 'Bangkok Airways',
    country: 'Thailand',
    region: 'Asia',
  },
  {
    code: 'PK',
    name: "Pakistan Int'l Airlines",
    country: 'Pakistan',
    region: 'Asia',
  },
  {
    code: 'PR',
    name: 'Philippine Airlines',
    country: 'Philippines',
    region: 'Asia',
  },
  {
    code: 'PS',
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    region: 'Europe',
  },
  {
    code: 'PX',
    name: 'Air Niugini',
    country: 'Papua New Guinea',
    region: 'Oceania',
  },
  {
    code: 'PY',
    name: 'Surinam Airways',
    country: 'Suriname',
    region: 'Latin America',
  },
  {
    code: 'PZ',
    name: 'TAM Airlines Paraguay',
    country: 'Paraguay',
    region: 'Latin America',
  },
  { code: 'QF', name: 'Qantas', country: 'Australia', region: 'Oceania' },
  {
    code: 'QK',
    name: 'Air Canada Jazz',
    country: 'Canada',
    region: 'North America',
  },
  {
    code: 'QR',
    name: 'Qatar Airways',
    country: 'Qatar',
    region: 'Middle East',
  },
  {
    code: 'QS',
    name: 'Smart Wings',
    country: 'Czech Republic',
    region: 'Europe',
  },
  {
    code: 'QX',
    name: 'Horizon Air',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'QZ',
    name: 'Indonesia AirAsia',
    country: 'Indonesia',
    region: 'Asia',
  },
  {
    code: 'RA',
    name: 'Nepal Airlines',
    country: 'Nepal',
    region: 'Asia',
  },
  {
    code: 'RB',
    name: 'Syrian Arab Airlines',
    country: 'Syria',
    region: 'Middle East',
  },
  {
    code: 'RC',
    name: 'Atlantic Airways',
    country: 'Faroe Islands',
    region: 'Europe',
  },
  { code: 'RE', name: 'Aer Arann', country: 'Ireland', region: 'Europe' },
  {
    code: 'RJ',
    name: 'Royal Jordanian',
    country: 'Jordan',
    region: 'Middle East',
  },
  { code: 'RO', name: 'Tarom', country: 'Romania', region: 'Europe' },
  {
    code: 'S7',
    name: 'S7 Airlines',
    country: 'Russia',
    region: 'Europe',
  },
  {
    code: 'SA',
    name: 'South African Airways',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'SC',
    name: 'Shandong Airlines',
    country: 'China',
    region: 'Asia',
  },
  { code: 'SG', name: 'SpiceJet', country: 'India', region: 'Asia' },
  {
    code: 'SJ',
    name: 'Sriwijaya Air',
    country: 'Indonesia',
    region: 'Asia',
  },
  {
    code: 'SK',
    name: 'Scandinavian Airlines (SAS)',
    country: 'Sweden',
    region: 'Europe',
  },
  {
    code: 'SN',
    name: 'Brussels Airlines',
    country: 'Belgium',
    region: 'Europe',
  },
  {
    code: 'SQ',
    name: 'Singapore Airlines',
    country: 'Singapore',
    region: 'Asia',
  },
  { code: 'ST', name: 'Germania', country: 'Germany', region: 'Europe' },
  { code: 'SU', name: 'Aeroflot', country: 'Russia', region: 'Europe' },
  {
    code: 'SV',
    name: 'Saudia',
    country: 'Saudi Arabia',
    region: 'Middle East',
  },
  {
    code: 'SW',
    name: 'Air Namibia',
    country: 'Namibia',
    region: 'Africa',
  },
  {
    code: 'SY',
    name: 'Sun Country Airlines',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'T5',
    name: 'Turkmenistan Airlines',
    country: 'Turkmenistan',
    region: 'Asia',
  },
  {
    code: 'TG',
    name: 'Thai Airways',
    country: 'Thailand',
    region: 'Asia',
  },
  {
    code: 'TK',
    name: 'Turkish Airlines',
    country: 'Turkey',
    region: 'Europe',
  },
  {
    code: 'TN',
    name: 'Air Tahiti Nui',
    country: 'French Polynesia',
    region: 'Oceania',
  },
  {
    code: 'TO',
    name: 'Transavia France',
    country: 'France',
    region: 'Europe',
  },
  {
    code: 'TP',
    name: 'TAP Portugal',
    country: 'Portugal',
    region: 'Europe',
  },
  { code: 'TR', name: 'Scoot', country: 'Singapore', region: 'Asia' },
  {
    code: 'TS',
    name: 'Air Transat',
    country: 'Canada',
    region: 'North America',
  },
  { code: 'TU', name: 'Tunisair', country: 'Tunisia', region: 'Africa' },
  {
    code: 'TW',
    name: "T'way Air",
    country: 'South Korea',
    region: 'Asia',
  },
  {
    code: 'TX',
    name: 'Air Caraibes',
    country: 'France',
    region: 'Europe',
  },
  { code: 'U2', name: 'easyJet', country: 'UK', region: 'Europe' },
  {
    code: 'U6',
    name: 'Ural Airlines',
    country: 'Russia',
    region: 'Europe',
  },
  {
    code: 'UA',
    name: 'United Airlines',
    country: 'USA',
    region: 'North America',
  },
  { code: 'UK', name: 'Vistara', country: 'India', region: 'Asia' },
  {
    code: 'UL',
    name: 'SriLankan Airlines',
    country: 'Sri Lanka',
    region: 'Asia',
  },
  {
    code: 'UM',
    name: 'Air Zimbabwe',
    country: 'Zimbabwe',
    region: 'Africa',
  },
  {
    code: 'UN',
    name: 'Transaero Airlines',
    country: 'Russia',
    region: 'Europe',
  },
  {
    code: 'UO',
    name: 'Hong Kong Express',
    country: 'Hong Kong',
    region: 'Asia',
  },
  {
    code: 'US',
    name: 'US Airways',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'UT',
    name: 'UTair Aviation',
    country: 'Russia',
    region: 'Europe',
  },
  { code: 'UX', name: 'Air Europa', country: 'Spain', region: 'Europe' },
  {
    code: 'V7',
    name: 'Air Senegal International',
    country: 'Senegal',
    region: 'Africa',
  },
  {
    code: 'VA',
    name: 'Virgin Australia',
    country: 'Australia',
    region: 'Oceania',
  },
  {
    code: 'VB',
    name: 'VivaAerobus',
    country: 'Mexico',
    region: 'Latin America',
  },
  { code: 'VJ', name: 'VietJet Air', country: 'Vietnam', region: 'Asia' },
  {
    code: 'VN',
    name: 'Vietnam Airlines',
    country: 'Vietnam',
    region: 'Asia',
  },
  {
    code: 'VS',
    name: 'Virgin Atlantic',
    country: 'United Kingdom',
    region: 'Europe',
  },
  {
    code: 'VT',
    name: 'Air Tahiti',
    country: 'French Polynesia',
    region: 'Oceania',
  },
  {
    code: 'VW',
    name: 'Aeromar',
    country: 'Mexico',
    region: 'Latin America',
  },
  {
    code: 'VY',
    name: 'Vueling Airlines',
    country: 'Spain',
    region: 'Europe',
  },
  { code: 'W6', name: 'Wizz Air', country: 'Hungary', region: 'Europe' },
  { code: 'WB', name: 'RwandAir', country: 'Rwanda', region: 'Africa' },
  { code: 'WF', name: 'Wideroe', country: 'Norway', region: 'Europe' },
  {
    code: 'WG',
    name: 'Sunwing Airlines',
    country: 'Canada',
    region: 'North America',
  },
  {
    code: 'WK',
    name: 'Edelweiss Air',
    country: 'Switzerland',
    region: 'Europe',
  },
  {
    code: 'WN',
    name: 'Southwest Airlines',
    country: 'USA',
    region: 'North America',
  },
  {
    code: 'WS',
    name: 'WestJet',
    country: 'Canada',
    region: 'North America',
  },
  {
    code: 'WY',
    name: 'Oman Air',
    country: 'Oman',
    region: 'Middle East',
  },
  {
    code: 'XL',
    name: 'LAN Ecuador',
    country: 'Ecuador',
    region: 'Latin America',
  },
  { code: 'XQ', name: 'SunExpress', country: 'Turkey', region: 'Europe' },
  {
    code: 'Y4',
    name: 'Volaris',
    country: 'Mexico',
    region: 'Latin America',
  },
  {
    code: 'YB',
    name: 'South African Express',
    country: 'South Africa',
    region: 'Africa',
  },
  {
    code: 'YM',
    name: 'Montenegro Airlines',
    country: 'Montenegro',
    region: 'Europe',
  },
  { code: 'YW', name: 'Air Nostrum', country: 'Spain', region: 'Europe' },
  {
    code: 'ZB',
    name: 'Monarch Airlines',
    country: 'United Kingdom',
    region: 'Europe',
  },
  {
    code: 'ZE',
    name: 'Eastar Jet',
    country: 'South Korea',
    region: 'Asia',
  },
  {
    code: 'ZH',
    name: 'Shenzhen Airlines',
    country: 'China',
    region: 'Asia',
  },
  { code: 'ZI', name: 'Aigle Azur', country: 'France', region: 'Europe' },
  {
    code: 'ZW',
    name: 'Air Wisconsin',
    country: 'USA',
    region: 'North America',
  },
];
